create database MiniLibaryManagementSystem;

go

use MiniLibaryManagementSystem;

go

CREATE TABLE BookManagementTable (
    BOOKID INT PRIMARY KEY IDENTITY(1,1),
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    ISBN VARCHAR(50) UNIQUE NOT NULL,
    CATEGORY VARCHAR(100),
    COPIESAVAILABLE INT DEFAULT 0,
    PUBLISHEDYEAR INT,
    STATUS INT DEFAULT 0,
    ISDELETE INT DEFAULT 0
);
GO

CREATE TABLE MemberManagementTable (
    MEMBERID INT PRIMARY KEY IDENTITY(1,1),
    FULLNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    JOINDATE DATETIME DEFAULT GETDATE(),
    ISACTIVE INT DEFAULT 1,
    ISDELETE INT DEFAULT 0
);
GO

CREATE TABLE BorrowDetailsTable (
    BORROWID INT PRIMARY KEY IDENTITY(1,1),
    MEMBERID INT NOT NULL,
    BORROWDATE DATETIME DEFAULT GETDATE(),
    DUEDATE DATETIME NOT NULL,
    RETURNDATE DATETIME NULL,
    ISDELETE INT DEFAULT 0,
    FOREIGN KEY (MEMBERID) REFERENCES MemberManagementTable(MEMBERID)
);
GO

CREATE TABLE BorrowBookListTable (
    ID INT PRIMARY KEY IDENTITY(1,1),
    BORROWID INT NOT NULL,
    BOOKID INT NOT NULL,
    ISDELETE INT DEFAULT 0,
    FOREIGN KEY (BORROWID) REFERENCES BorrowDetailsTable(BORROWID),
    FOREIGN KEY (BOOKID) REFERENCES BookManagementTable(BOOKID)
);
GO

CREATE TABLE DueAttaterEmailLog (
    ID INT PRIMARY KEY IDENTITY(1,1),
    EMAIL VARCHAR(255) NOT NULL,
    MESSAGE NVARCHAR(MAX),
    SENDDATE DATETIME NOT NULL
    FOREIGN KEY (EMAIL) REFERENCES MemberManagementTable(EMAIL)
);
GO

